name: FactionsPro
author: Fearless
description: A Extended Factions plugin. [Beta Branch]
version: 2.1.6
main: FactionsPro\FactionMain
api: [3.0.0]
softdepend: ["PureChat", "AntiSpamPro", "EconomyAPI"]
extensions: [sqlite3]
commands:
  f:
    description: Faction commands.
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Allow use of all faction commands"
